# Generated by Django 4.1.7 on 2023-03-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_alter_claim_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="claim",
            old_name="location",
            new_name="city",
        ),
        migrations.AlterField(
            model_name="claim",
            name="cause",
            field=models.CharField(
                choices=[
                    (1, "Road Traffic Accident"),
                    (2, "Accident At Home"),
                    (3, "Accident At Work"),
                    (4, "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
