# Generated by Django 4.1.7 on 2023-03-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_rename_location_claim_city_alter_claim_cause"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="number_of_dependants",
        ),
        migrations.AddField(
            model_name="claim",
            name="number_of_dependents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="claim",
            name="fee_charged",
            field=models.FloatField(default=0.0),
        ),
    ]
