# Generated by Django 4.1.7 on 2023-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0005_alter_claim_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[("Fraud", "Fraud"), ("Clean", "Clean"), (None, None)],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="cause",
            field=models.CharField(
                choices=[
                    ("RTA", "Road Traffic Accident"),
                    ("AAH", "Accident At Home"),
                    ("AAW", "Accident At Work"),
                    ("O", "Other"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("S", "Single"),
                    ("H", "Husband"),
                    ("W", "Wife"),
                    ("B", "Brother"),
                    ("s", "Sister"),
                    ("A", "Aunt"),
                    ("G", "Grandmother"),
                    ("U", "Uncle"),
                    ("G", "Grandfather"),
                    ("N", "Nephew"),
                    ("n", "Niece"),
                    ("O", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
