# Generated by Django 4.1.7 on 2023-03-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0006_claim_classification_alter_claim_cause_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="claim",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Husband", "Husband"),
                    ("Wife", "Wife"),
                    ("Brother", "Brother"),
                    ("Sister", "Sister"),
                    ("Aunt", "Aunt"),
                    ("Grandmother", "Grandmother"),
                    ("Uncle", "Uncle"),
                    ("Grandfather", "Grandfather"),
                    ("Nephew", "Nephew"),
                    ("Niece", "Niece"),
                    ("Other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
