# Generated by Django 4.1.7 on 2023-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certificatevalidation",
            name="certificate",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="certificatevalidation",
            name="status",
            field=models.CharField(
                choices=[("Fraud", "Fraud"), ("Clean", "Clean")], max_length=30
            ),
        ),
    ]
