# Generated by Django 4.1.7 on 2023-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_alter_certificate_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatevalidation",
            name="certificate",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
