# Generated by Django 4.1.7 on 2023-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_alter_certificatevalidation_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
