# Generated by Django 4.1.7 on 2023-03-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service_providers", "0002_alter_serviceprovider_created_at_and_more"),
        ("certificates", "0004_alter_certificate_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="service_provider",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_certificate",
                to="service_providers.serviceprovider",
            ),
        ),
    ]
