# Generated by Django 4.1.7 on 2023-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0005_certificate_service_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatevalidation",
            name="title",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="certificatevalidation",
            name="certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="uploade_certificates/"
            ),
        ),
    ]
