# Generated by Django 4.1.7 on 2023-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0006_certificatevalidation_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatevalidation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Fraud", "Fraud"), ("Clean", "Clean")],
                max_length=30,
                null=True,
            ),
        ),
    ]
