# Generated by Django 4.1.7 on 2023-03-11 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0009_alter_certificate_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="hash",
            field=models.TextField(
                default=uuid.UUID("e9d1f9e3-c856-4453-a954-f6dc94fe5942")
            ),
        ),
    ]
