# Generated by Django 3.2 on 2023-03-11 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_alter_certificate_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='hash',
            field=models.TextField(default=uuid.UUID('868d87b8-8c2f-43f1-ab19-812859d6a88b')),
        ),
    ]
