# Generated by Django 4.1.7 on 2023-03-11 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_alter_certificate_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='hash',
            field=models.TextField(default=uuid.UUID('6e6f6729-e233-438b-aaef-2c6c00aef790')),
        ),
    ]
