# Generated by Django 4.1.7 on 2023-03-11 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0010_alter_certificate_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="hash",
            field=models.TextField(
                default=uuid.UUID("ad101f3c-597a-4406-9e46-720ef981db5d")
            ),
        ),
    ]
