# Generated by Django 4.1.7 on 2023-03-25 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0012_alter_certificate_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="hash",
            field=models.TextField(
                default=uuid.UUID("08b85f76-9514-4835-a8c8-ad788d098239")
            ),
        ),
    ]
