# Generated by Django 4.1.7 on 2023-03-25 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0013_alter_certificate_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="hash",
            field=models.TextField(
                default=uuid.UUID("1055943f-defe-40b7-8a17-2897c8e1a7e6")
            ),
        ),
    ]
