# Generated by Django 4.1.7 on 2023-03-29 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0014_alter_certificate_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="hash",
            field=models.TextField(
                default=uuid.UUID("821043ea-e038-4a91-8086-2fac9577555c")
            ),
        ),
    ]
