# Generated by Django 4.1.7 on 2023-03-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_providers", "0002_alter_serviceprovider_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceprovider",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="serviceprovider",
            old_name="updated_at",
            new_name="updated",
        ),
        migrations.RemoveField(
            model_name="serviceprovider",
            name="certificate",
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="website",
            field=models.URLField(max_length=255),
        ),
    ]
